# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

services:
  mempool-stub:
    image: ghcr.io/sygmaprotocol/beacon-api-stub
    volumes:
      - "./cfg/stubs:/stubs"
    ports:
      - 8882:8882
    environment:
      - STUB_DATA=/stubs/mempool.yml

  bitcoin:
#   image: ruimarinho/bitcoin-core:latest
    image: ghcr.io/sygmaprotocol/bitcoin
    container_name: bitcoin
    ports:
      - "18443:18443"
      - "18332:18332"
    environment:
      BITCOIN_RPC_USER: user
      BITCOIN_RPC_PASSWORD: password
      BITCOIN_RPC_PORT: 18443
      BITCOIN_NETWORK: regtest
      BITCOIN_EXTRA_ARGS: "-rpcallowip=0.0.0.0/0 -rpcbind=0.0.0.0"
    volumes:
      - ./cfg/entrypoint/entrypoint.sh:/cfg/entrypoint/entrypoint.sh
    entrypoint: /cfg/entrypoint/entrypoint.sh

  evm1-1:
    image: ghcr.io/sygmaprotocol/sygma-solidity:evm1-v2.7.0
    container_name: evm1-1
    command: ganache-cli --chainId 1337 -d --db data/ --blockTime 2 > /dev/null
    logging:
      driver: none
    ports:
      - "8545:8545"

  evm2-1:
    image: ghcr.io/sygmaprotocol/sygma-solidity:evm2-v2.7.0
    command: ganache-cli --chainId 1338 -d --db data/ --blockTime 2 > /dev/null
    container_name: evm2-1
    logging:
      driver: none
    ports:
      - "8547:8545"

  substrate-pallet:
    container_name: substrate-pallet
    image: "ghcr.io/sygmaprotocol/sygma-substrate-pallets:e2e-v0.3.1"
    ports:
      - "9944:9944"
      - "9933:9933"
      
  ipfs0:
    container_name: ipfs0
    image: ipfs/kubo:release
    ports:
      - "4001:4001" 
      - "5002:5001" 
      - "8080:8080" 


  relayer1:
    container_name: example_relayer1
    build:
      context: ../.
      dockerfile: ./example/Dockerfile
    command: sh -c "sleep 5 && ./bridge run --config /cfg/config_evm-evm_1.json --fresh"
    depends_on:
      - evm1-1
      - substrate-pallet
    volumes:
      - ./cfg:/cfg
    restart: always

  relayer2:
    container_name: example_relayer2
    build:
      context: ../.
      dockerfile: ./example/Dockerfile
    command: sh -c "sleep 5 && ./bridge run --config /cfg/config_evm-evm_2.json --fresh"
    depends_on:
      - evm1-1
      - substrate-pallet
    volumes:
      - ./cfg:/cfg
    restart: always

  relayer3:
    container_name: example_relayer3
    build:
      context: ../.
      dockerfile: ./example/Dockerfile
    command: sh -c "sleep 5 && ./bridge run --config /cfg/config_evm-evm_3.json --fresh"
    depends_on:
      - evm1-1
      - substrate-pallet
    volumes:
      - ./cfg:/cfg
    restart: always

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./cfg/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "8889:8889"   # Prometheus exporter metrics
