name: Deploy ECS relayers

on:
  pull_request:
  
  # push:
  #   branches:
  #     - main

env:
  AWS_REGION: "us-east-2"
  ECR_REPOSITORY: relayer-0-stage
  ENVIRONMENT: STAGE
  AWS_STAGE: '${{ secrets.AWS_ARN }}'

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-18.04

    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: true
      matrix:
        relays: [0,1,2,3,4]
    
    steps:
      - uses: actions/checkout@v2
      - run: sleep 5
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_STAGE }}:role/github-actions-${{ env.ENVIRONMENT }}-chainbridge
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GithubActions

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.ENVIRONMENT }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.ENVIRONMENT }}

      - name: Deploy to Amazon ECS - Relayers
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs/task_definition-${{ matrix.relays }}_${{ env.ENVIRONMENT }}.json
          service: relayer-${{ matrix.relays }}-service-${{ env.ENVIRONMENT }}
          cluster: relayer-${{ env.ENVIRONMENT }}
          wait-for-service-stability: true
