# The Licensed Work is (c) 2022 Sygma
# SPDX-License-Identifier: BUSL-1.1

name: Deploy ECS relayer 1

on:
  push:
    branches:
      - main

env:
  AWS_REGION: "us-east-2"
  ECR_REPOSITORY: relayer-0
  ENVIRONMENT: PROD

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v2
      - run: sleep 5
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::852551629426:role/github-actions-${{ env.ENVIRONMENT }}-chainbridge
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GithubActions

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:stable .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:stable

      - name: Deploy to Amazon ECS - Relayer 1
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs/task_definition-1_${{ env.ENVIRONMENT }}.json
          service: relayer-1-service-${{ env.ENVIRONMENT }}
          cluster: relayer-${{ env.ENVIRONMENT }}
          wait-for-service-stability: true
