# The Licensed Work is (c) 2022 Sygma
# SPDX-License-Identifier: LGPL-3.0-only

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: E2E tests
jobs:
  e2e:
    name: E2E Tests
    strategy:
      matrix:
        go-version: [ 1.19.x ]
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run nodes
        run: docker-compose -f ./example/docker-compose.yml up -d
      - name: Run tests
        run: make e2e-test
      - name: Print logs
        if: always()
        run: |
          docker ps -a
          docker logs example_relayer1
